#!/bin/sh
#
# My https://pair.io dotfiles bootstrap script.
#
# Usage:
# curl https://raw.github.com/zkim/.pair.io/master/bootstrap | sh

IAM=$(whoami)
DOT_ROOT=~/.zkim-pairio-dotfiles

rm -rf ~/.oh-my-zsh
rm -rf $DOT_ROOT

unlink ~/.emacs.d
unlink ~/.bash_profile
unlink ~/.bashrc
unlink ~/.gitconfig
unlink ~/.tmux.conf
unlink ~/.zshrc

git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
git clone https://github.com/zkim/.pair.io.git ~/.zkim-pairio-dotfiles
				
ln -s -t ~/ $DOT_ROOT/.emacs.d
ln -s -t ~/ $DOT_ROOT/.bash_profile
ln -s -t ~/ $DOT_ROOT/.bashrc
ln -s -t ~/ $DOT_ROOT/.gitconfig
ln -s -t ~/ $DOT_ROOT/.tmux.conf
ln -s -t ~/ $DOT_ROOT/.zshrc

cp -f -v $DOT_ROOT/.oh-my-zsh/custom/*.zsh ~/.oh-my-zsh/custom/
cp -f -v $DOT_ROOT/.oh-my-zsh/themes/dakrone.zsh-theme ~/.oh-my-zsh/themes/

sudo apt-get install -y exuberant-ctags
